name: Build and Publish YouTube SDK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env:
  NODE_VERSION: '20'

jobs:
  generate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@bison.digital'

      - name: Install dependencies
        run: npm install

      - name: Generate SDK code
        run: |
          echo "Generating YouTube SDK from OpenAPI spec..."
          
          # Remove lockfiles to avoid version conflicts
          rm -f .skmtc/moral-termite-562/deno.lock
          rm -f .skmtc/moral-termite-562/gen-basic-sdk/deno.lock
          
          # Run the SKMTC CLI to generate SDK code
          deno run -A --unstable-kv jsr:@skmtc/cli generators:generate moral-termite-562 .
          
          echo "Generator completed successfully!"
          echo "Generated files:"
          find src -name "*.ts" -type f | head -10

      - name: Fix imports and generate types index
        run: |
          echo "Fixing imports and generating types index..."
          
          # Use our automated scripts to fix imports and generate types index
          node fix-imports.js
          node generate-types-index.js
          
          echo "✅ Fixed imports and generated types index"
          
      - name: Verify generated SDK
        run: |
          echo "Verifying generated files..."
          echo "✅ Generated files:"
          ls -la src/
          echo ""
          echo "Generated types index:"
          head -5 src/types/index.ts
          echo ""
          echo "✅ Ready to build"

      - name: Build package
        run: |
          # Use our build process that handles all the fixes
          npm run build

      - name: Run tests (if any)
        run: |
          # Add test command when tests are available
          echo "No tests configured yet"

      - name: Publish to NPM (on release)
        if: github.event_name == 'release'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7