name: Build and Publish YouTube SDK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env:
  NODE_VERSION: '20'

jobs:
  generate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@bison.digital'

      - name: Install dependencies
        run: npm install

      - name: Generate SDK code
        run: |
          echo "Generating YouTube SDK from OpenAPI spec..."
          
          # Remove lockfiles to avoid version conflicts
          rm -f .skmtc/pregnant-tuna-704/deno.lock
          rm -f .skmtc/pregnant-tuna-704/gen-basic-sdk/deno.lock
          
          # Run the SKMTC CLI to generate SDK code
          deno run -A --unstable-kv jsr:@skmtc/cli@^0.0.153 generators:generate pregnant-tuna-704 .
          
          echo "Generator completed successfully!"
          echo "Generated files:"
          find src -name "*.ts" -type f | head -10

      - name: Check generated files
        run: |
          echo "✅ Generated files:"
          ls -la src/
          echo ""
          echo "Generated client (first 10 lines):"
          head -10 src/YouTubeClient.generated.ts
          echo ""
          echo "Generated types:"
          ls -la src/types/ | grep "\.generated\." | head -5
          
      - name: Verify generated SDK
        run: |
          echo "Verifying generated files..."
          if [ -d "src" ] && [ "$(ls -A src 2>/dev/null)" ]; then
            echo "✅ src directory contains generated files"
            ls -la src/
            echo "Generated client methods:"
            grep -n "async.*Api" src/YouTubeClient.generated.ts | head -5 || echo "No API methods found"
          else
            echo "❌ No files generated in src directory"
            exit 1
          fi

      - name: Build package
        run: |
          # Build the TypeScript package
          npx tsc
          npx rollup -c

      - name: Run tests (if any)
        run: |
          # Add test command when tests are available
          echo "No tests configured yet"

      - name: Publish to NPM (on release)
        if: github.event_name == 'release'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7