name: Build and Publish YouTube SDK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env:
  NODE_VERSION: '20'

jobs:
  generate-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@bison.digital'

      - name: Install dependencies
        run: npm install

      - name: Generate SDK code
        run: |
          # Run the SKMTC CLI to generate SDK code (not just TypeScript utilities)
          echo "Generating YouTube SDK from OpenAPI spec..."
          
          # First, let's see what generation options are available
          echo "Available generation options:"
          deno run -A --unstable-kv jsr:@skmtc/cli@^0.0.153 --help || true
          
          # Try to generate actual SDK client code
          echo "Attempting different SDK generation targets..."
          deno run -A --unstable-kv jsr:@skmtc/cli@^0.0.153 --project=pregnant-tuna-704 --generate --target=client || true
          echo "Trying basic-sdk target..."
          deno run -A --unstable-kv jsr:@skmtc/cli@^0.0.153 --project=pregnant-tuna-704 --generate --target=basic-sdk || true
          echo "Trying sdk target..."
          deno run -A --unstable-kv jsr:@skmtc/cli@^0.0.153 --project=pregnant-tuna-704 --generate --target=sdk || true
          echo "Default generation..."
          deno run -A --unstable-kv jsr:@skmtc/cli@^0.0.153 --project=pregnant-tuna-704 --generate || true
          
          # Create src directory if it doesn't exist
          mkdir -p src
          
          # List what was generated for debugging
          echo "Available generated directories:"
          find .skmtc/pregnant-tuna-704 -type d -name "gen-*" || echo "No gen- directories found"
          
          # Check what's in each generated directory
          echo "Checking gen-zod contents:"
          if [ -d ".skmtc/pregnant-tuna-704/gen-zod" ]; then
            find .skmtc/pregnant-tuna-704/gen-zod -name "*.ts" -type f | head -10
            echo "Sample gen-zod file:"
            find .skmtc/pregnant-tuna-704/gen-zod -name "*.ts" -type f | head -1 | xargs cat | head -20
          fi
          
          echo "Checking gen-typescript contents:"
          if [ -d ".skmtc/pregnant-tuna-704/gen-typescript" ]; then
            find .skmtc/pregnant-tuna-704/gen-typescript -name "*.ts" -type f | head -10
          fi
          
          # For now, let's try to create our own SDK using gen-zod types
          if [ -d ".skmtc/pregnant-tuna-704/gen-zod" ]; then
            echo "Using gen-zod for API types and creating custom SDK"
            GENERATED_DIR=".skmtc/pregnant-tuna-704/gen-zod"
          else
            echo "No suitable generated directory found, failing build"
            exit 1
          fi
          
          echo "Using generated directory: $GENERATED_DIR"
          
          # Copy all TypeScript files, maintaining directory structure
          if [ -d "$GENERATED_DIR" ]; then
            # Copy everything first
            cp -r "$GENERATED_DIR"/* src/
            
            # If there's a mod.ts (Deno style), rename it to index.ts
            if [ -f "src/mod.ts" ]; then
              echo "Found Deno-style mod.ts, renaming to index.ts"
              mv src/mod.ts src/index.ts
            fi
          fi
          
          # List what we have in src now
          echo "Generated files in src:"
          find src -type f -name "*.ts" | head -30 || echo "No TypeScript files in src"

      - name: Verify generated SDK classes
        run: |
          echo "Checking what SDK classes were generated..."
          find src -name "*.ts" -type f -exec grep -l "class.*Client\|export.*Client" {} \; || echo "No client classes found"
          find src -name "*.ts" -type f -exec grep -l "export.*Client\|export class" {} \; | head -5 || echo "No exported classes found"

      - name: Fix import paths
        run: |
          # Fix Deno-style imports to Node.js-style imports
          echo "Fixing import paths for Node.js compatibility..."
          
          # Convert ./src/ paths to relative paths
          find src -name "*.ts" -exec sed -i 's|from '"'"'./src/|from '"'"'./|g' {} \;
          
          # Convert .ts extensions to .js for Node.js
          find src -name "*.ts" -exec sed -i 's|\.ts'"'"';|.js'"'"';|g' {} \;
          
          # Convert @/ aliases to relative paths  
          find src -name "*.ts" -exec sed -i 's|from '"'"'@/|from '"'"'./|g' {} \;
          
          # Show what the imports look like now
          echo "Sample of fixed imports:"
          grep -n "from '" src/index.ts | head -5 || echo "No imports found in index.ts"

      - name: Build package
        run: |
          npx tsc
          npx rollup -c

      - name: Run tests (if any)
        run: |
          # Add test command when tests are available
          echo "No tests configured yet"

      - name: Publish to NPM (on release)
        if: github.event_name == 'release'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7